Repository MetricsHub/community-connectors, pull requests merged in 2025-03, with the labels that each got.

#182 Issue #24: Move semantic conventions yaml to semconv
  src/main/connector/database/MySQL/MySQL.yaml
  src/main/connector/hardware/DiskPart/DiskPart.yaml
  src/main/connector/hardware/GenBatteryNT/GenBatteryNT.yaml
  src/main/connector/hardware/GenericSwitchEnclosure/GenericSwitchEnclosure.yaml
  src/main/connector/hardware/GenericUPS/GenericUPS.yaml
  src/main/connector/hardware/HyperV/HyperV.yaml
  src/main/connector/hardware/IpmiTool/IpmiTool.yaml
  src/main/connector/hardware/LibreHardwareMonitor/LibreHardwareMonitor.yaml
  src/main/connector/hardware/LinuxMultipath/LinuxMultipath.yaml
  src/main/connector/hardware/LinuxNetwork/LinuxIPNetwork/LinuxIPNetwork.yaml
  src/main/connector/hardware/LinuxNetwork/LinuxIfConfigNetwork/LinuxIfConfigNetwork.yaml
  src/main/connector/hardware/MIB2/MIB2.yaml
  src/main/connector/hardware/MIB2Linux/MIB2Linux.yaml
  src/main/connector/hardware/MIB2NT/MIB2NT.yaml
  src/main/connector/hardware/MIB2Switch/MIB2Switch.yaml
  src/main/connector/hardware/NvidiaSmi/NvidiaSmi.yaml
  src/main/connector/hardware/Virsh/Virsh.yaml
  src/main/connector/hardware/WBEMGenDiskNT/WBEMGenDiskNT.yaml
  src/main/connector/hardware/WBEMGenHBA/WBEMGenHBA.yaml
  src/main/connector/hardware/WBEMGenLUN/WBEMGenLUN.yaml
  src/main/connector/hardware/WBEMGenNetwork/WBEMGenNetwork.yaml
  src/main/connector/hardware/WinStorageSpaces/WinStorageSpaces.yaml
  src/main/connector/hardware/lmsensors/lmsensors.yaml
  src/main/connector/semconv/Database.yaml
  src/main/connector/semconv/Hardware.yaml
  src/main/connector/semconv/Storage.yaml
  src/main/connector/semconv/System.yaml
  src/main/connector/system/Linux/Linux.yaml
  src/main/connector/system/LinuxProcess/LinuxProcess.yaml
  src/main/connector/system/LinuxService/LinuxService.yaml
  src/main/connector/system/Windows/Windows.yaml
  src/main/connector/system/WindowsProcess/WindowsProcess.yaml
  src/main/connector/system/WindowsService/WindowsService.yaml
Labels: enhancement, developer_tested

#191 Issue #190: Add db.server.name as an attribute in MySQL
  src/main/connector/database/MySQL/MySQL.yaml
Labels: enhancement

#192 Issue #187: Fix Linux connector network and file system issues
  src/main/connector/system/Linux/Linux.yaml
Labels: bug

#189 Issue #188: Update database yaml
  src/main/connector/semconv/Database.yaml
Labels: enhancement
